const data = [
  {
    id: 1,
    module: "1. Learn and Explore HTML as a Beginner",

    description: [
      <li>1.1 Getting started with your first ever website</li>,
      <br />,
      <li>1.2 HTML language, markup, tags structure, paragraph tag</li>,
      <br />,
      <li>1.3 Bold, strong, how HTML tag works</li>,
      <br />,
      <li>1.4 HTML tag attribute, anchor, href, navigate</li>,
      <br />,
      <li>1.5 Display image (online image, local image, folder image)</li>,
      <br />,
      <li>1.6 List, container tag, ordered list, unordered list</li>,
      <br />,
      <li>1.7 Button, input, div, span, w3schools, every html tags</li>,
      <br />,
      <li>1.8 HTML structure, head, body, title, meta tag</li>,
      <br />,
      <li>1.9 HTML Module Summary, 4 types of HTML tags</li>,
      <br />,
    ],
  },
  {
    id: 2,
    module: "2. Learn and Explore CSS as a Beginner",
    description: [
      <li>2.1 Introduction to CSS Module, getting started with CSS</li>,
      <br />,
      <li>2.2 Style tag, embedded style, named color, hexcode, rgb</li>,
      <br />,
      <li>2.3 Background-color, height, width, font, CSS measuring units</li>,
      <br />,
      <li>2.4 CSS ID, apply styles to a specific HTML element</li>,
      <br />,
      <li>2.5 CSS class, apply styles to multiple elements, ID vs Class</li>,
      <br />,
      <li>2.6 Style a group of elements, style a small portion of text</li>,
      <br />,
      <li>2.7 Border, border radius, margin, different ways to set margin</li>,
      <br />,
      <li>2.8 Padding, different ways to set padding, CSS Box model</li>,
      <br />,
      <li>
        2.9 Text align, float, display, inline, block, inline-block, external
        CSS
      </li>,
      <br />,
      <li>2.10 CSS Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 3,
    module: "3. Git, source control, GitHub and hosting",
    description: [
      <li>3.1 What is GitHub?</li>,
      <br />,
      <li>3.2 Install git, create GitHub repository</li>,
      <br />,
      <li>3.3 Git init, git add, git commit, set origin</li>,
      <br />,
      <li>3.4 Git push, git pull</li>,
      <br />,
      <li>3.5 How to use Github Desktop software to use Github</li>,
      <br />,
      <li>
        3.6 [advanced: feel free to skip] git branch and this will confuse you
      </li>,
      <br />,
      <li>3.7 Common git related issues faced by new github users</li>,
      <br />,
      <li>
        3.8 [advanced: feel free to skip] GitHub hosting complicated things
      </li>,
      <br />,
      <li>3.9 Github hosting related common issues</li>,
      <br />,
      <li>3.10 GitHub overall summary</li>,
      <br />,
    ],
  },
  {
    id: 3.5,
    module: "3_5. [Bonus] CSS Extra hover, position, specificity, homework",
    description: [
      <li>3_5.1 pseudoclass part hover all elements, hover special</li>,
      <br />,
      <li>
        3_5.2 pseudoclass focus first child, last child, nth child, visited
      </li>,
      <br />,
      <li>3_5.3 pseudo element before after</li>,
      <br />,
      <li>3_5.4 css position static relative absolute fixed</li>,
      <br />,
      <li>3_5.5 CSS specificity style order style priority</li>,
      <br />,
      <li>3_5.6 css homework and learn by yourself</li>,
      <br />,
    ],
  },
  {
    id: 4,
    module: "4. Build a beautiful and professional portfolio website",
    description: [
      <li>4.1 Module Introduction, overview of the site you will build</li>,
      <br />,
      <li>4.2 Setup and resources needed to start your first ever project</li>,
      <br />,
      <li>4.3 Create HTML, link CSS, set title, span tag style</li>,
      <br />,
      <li>4.4 Simple image background remove, set fancy background</li>,
      <br />,
      <li>
        4.5 Float, create container, put two div side by side, image size
      </li>,
      <br />,
      <li>
        4.6 Background image, background-repeat, neutralize default style
      </li>,
      <br />,
      <li>4.7 Link button, target blank, text-decoration, linear gradient</li>,
      <br />,
      <li>4.8 Dream image, half-width, background remove</li>,
      <br />,
      <li>4.9 Dream area, dream text and download resume link button</li>,
      <br />,
      <li>4.10 Experience area, text highlight, meaningful class name</li>,
      <br />,
      <li>4.11 Box shadow, border image, gradient angle, footer</li>,
      <br />,
      <li>4.12 Website hosting, live portfolio link, portfolio summary</li>,
      <br />,
    ],
  },
  {
    id: 5,
    module: "5. Personal website, build a brand new website",
    description: [
      <li>5.1 Personal website, build a complete website by yourself</li>,
      <br />,
      <li>Personal Website Assignment – Updated</li>,
      <br />,
    ],
  },
  {
    id: 6,
    module: "6. HTML 5 Semantic tags, audio, video, table, form",
    description: [
      <li>6.1 audio, video, youtube video, Audio video (iframe)</li>,
      <br />,
      <li>6.2 HTML5 Semantic tags section article aside mark</li>,
      <br />,
      <li>6.3 html table tbody thead td th caption and table style</li>,
      <br />,
      <li>6.4 html form input label fieldset legend textarea submit</li>,
      <br />,
      <li>6.5 others (favicon comments attributes option closing tag )</li>,
      <br />,
      <li>6.6 Module Summary HTML5</li>,
      <br />,
    ],
  },
  {
    id: 7,
    module: "7. CSS3 overflow, transition, transform, flexbox, grid layout",
    description: [
      <li>7.1 CSS3 Module Introduction</li>,
      <br />,
      <li>7.2 CSS Overflow hidden overflow scroll</li>,
      <br />,
      <li>7.3 Optimize images, types of images, svg, png, jpg</li>,
      <br />,
      <li>7.4 css transform and use multiple transform at the same time</li>,
      <br />,
      <li>7.5 transition of css property over time</li>,
      <br />,
      <li>7.6 Create simple cricket match with transition and transform</li>,
      <br />,
      <li>7.7 css animation and bounce effect with balls</li>,
      <br />,
      <li>7.8 flexbox, flex direction justify content align items</li>,
      <br />,
      <li>7.9 CSS Grid layout template columns grid gap</li>,
      <br />,
      <li>7.10 create calendar using css grid and flex box</li>,
      <br />,
      <li>7.11 css media query based on device and using flexbox</li>,
      <br />,
      <li>7.12 CSS3 and intermediate css module summary</li>,
      <br />,
    ],
  },
  {
    id: 8,
    module: "8. Learn and Explore Bootstrap",
    description: [
      <li>8.1 Module Introduction, Purpose of Bootstrap</li>,
      <br />,
      <li>8.2 Getting started with Bootstrap</li>,
      <br />,
      <li>8.3 Buttons, text color, background color, color palette</li>,
      <br />,
      <li>8.4 Image, responsive image, width style, image thumbnail</li>,
      <br />,
      <li>8.5 Website card, card design, card image, card deck</li>,
      <br />,
      <li>8.6 Nav tag, navigation, nav bar, use ul-li for navigation</li>,
      <br />,
      <li>8.7 Website layout, Responsive website</li>,
      <br />,
      <li>8.8 Grid layout, row, column, 12 column layout</li>,
      <br />,
      <li>8.9 Responsive grid, responsive breakpoints</li>,
      <br />,
      <li>8.10 Top banner animation, image slide, carousel</li>,
      <br />,
      <li>8.11 Flex layout, element align, vertical and horizontal center</li>,
      <br />,
      <li>8.12 Bootstrap Overview, Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 9,
    module: "9. Develop an e-commerce website using Bootstrap",
    description: [
      <li>9.1 Website overview and different section that you will build</li>,
      <br />,
      <li>9.2 Project setup, GitHub repository, project resources</li>,
      <br />,
      <li>9.3 Container, navbar, navbar item, links</li>,
      <br />,
      <li>9.4 Simple top banner carousel, set image for carousel</li>,
      <br />,
      <li>9.5 Advanced carousel with row and column divide</li>,
      <br />,
      <li>9.6 Vertical center in carousel item, button style</li>,
      <br />,
      <li>9.7 Categories, column gap, category in each row</li>,
      <br />,
      <li>9.8 Shoe category, card-deck, card box shadow</li>,
      <br />,
      <li>9.9 Backpack category, card footer, align button</li>,
      <br />,
      <li>9.10 Subscribe section, horizontal and vertical center</li>,
      <br />,
      <li>9.11 Footer, small tag, text center align</li>,
      <br />,
      <li>9.12 Project Summary, Code Recap</li>,
      <br />,
    ],
  },
  {
    id: 9.5,
    module: "9_5. Hot Gadgets, e-commerce website by yourself",
    description: [<li>9_5.1 Hot Gadgets, e-commerce website by yourself</li>],
  },
  {
    id: 10,
    module: "10. Landing Page Milestone Assignment",
    description: [
      <li>
        10.1 Electronic school Responsive bootstrap landing page assignment
      </li>,
      <br />,
      <li>Bootstrap landing page assignment updated</li>,
      <br />,
    ],
  },
  {
    id: 11,
    module: "11. CSS Bonus Content",
    description: [
      <li>11.1 css position more explanation relative absolute</li>,
      <br />,
      <li>11.2 Apply relative position in a photo album</li>,
      <br />,
      <li>11.3 Apply transition transform in a practical situation</li>,
      <br />,
      <li>11.4 CSS Grid Layout Extra explanation and compare with flexbox</li>,
      <br />,
      <li>11.5 More discussion about display inline block inline-block</li>,
      <br />,
      <li>11.6 git feature branch and bug fix branch</li>,
      <br />,
      <li>11.7 inline css when and how to use inline css</li>,
      <br />,
      <li>11.8 How to start working on a responsive website</li>,
      <br />,
      <li>
        11.9 Setup navigation bar with bootstrap for a responsive website
      </li>,
      <br />,
      <li>11.10 Setting profiles rows padding and images</li>,
      <br />,
      <li>11.11 Responsive and gap to set three two or one items</li>,
      <br />,
      <li>11.12 Module summary</li>,
      <br />,
    ],
  },
  {
    id: 11.5,
    module: "11_5. Revision Day 2",
    description: [
      <li>11_5.1 Revise and revisit bootstrap</li>,
      <br />,
      <li>11_5.2 Install Node and run node in Visual Studio Code</li>,
      <br />,
    ],
  },
  {
    id: 12,
    module: "12. Getting started with JavaScript",
    description: [
      <li>12.1 Module overview, need for JavaScript</li>,
      <br />,
      <li>12.2 Run JavaScript in browser, run JavaScript in VSCode</li>,
      <br />,
      <li>12.3 What is variable, declare a variable, see output</li>,
      <br />,
      <li>12.4 Variable type, Numeric, String, Boolean</li>,
      <br />,
      <li>12.5 variable name naming convention and best practice</li>,
      <br />,
      <li>12.6 explore string case change insex split</li>,
      <br />,
      <li>12.7 integer float parseInt parseFloat type conversion</li>,
      <br />,
      <li>12.8 Mathematical operations in JavaScript</li>,
      <br />,
      <li>12.9 Math absolute round floor ceil random</li>,
      <br />,
      <li>12.10 Make conditional decision, if-else, comparison</li>,
      <br />,
      <li>12.11 Multiple conditions, fulfill both conditions, else if</li>,
      <br />,
      <li>12.12 JavaScript Date timezone and Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 13,
    module: "13. JavaScript Fundamental Concepts",
    description: [
      <li>13.1 Fundamental JavaScript Module Introduction</li>,
      <br />,
      <li>13.2 Array, index, set by index, indexOf</li>,
      <br />,
      <li>13.3 Array advanced, push, pop, array length</li>,
      <br />,
      <li>13.4 array add and remove element from the beginning and slice</li>,
      <br />,
      <li>13.5 While loop, debug JavaScript code, less or equal</li>,
      <br />,
      <li>13.6 For loop, run a loop for each element of an array</li>,
      <br />,
      <li>13.7 javascript switch case break and default</li>,
      <br />,
      <li>13.8 Function, call function</li>,
      <br />,
      <li>13.9 Function parameter, multiple parameter, function return</li>,
      <br />,
      <li>13.10 Comment, multiple lines comment</li>,
      <br />,
      <li>13.11 Object, key value pair, get object property, set value</li>,
      <br />,
      <li>13.12 Basic JavaScript Overview, Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 14,
    module: "14. Apply Javascript Concepts",
    description: [
      <li>14.1 Module Introduction Apply JS</li>,
      <br />,
      <li>14.2 Unit Convert Inch to Feet use variable and function</li>,
      <br />,
      <li>14.3 variable let and const and how to use them</li>,
      <br />,
      <li>14.4 check whether a year is a Leap Year or not</li>,
      <br />,
      <li>14.5 Calculate Factorial of a number using for loop</li>,
      <br />,
      <li>14.6 Calculate Factorial of a number using a while loop</li>,
      <br />,
      <li>14.7 Calculate Factorial in a Recursive function</li>,
      <br />,
      <li>14.8 Create a Fibonacci Series using a for loop</li>,
      <br />,
      <li>14.9 Fibonacci Element in a Recursive Way</li>,
      <br />,
      <li>14.10 create Fibonacci series in a recursive way</li>,
      <br />,
      <li>14.11 Check whether a number is a Prime Number or not</li>,
      <br />,
      <li>14.12 Apply Basic JavaScript Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 15,
    module: "15. JavaScript Coding Problems, Simple Interview Questions",
    description: [
      <li>15.1 Module Introduction, Problem Setup</li>,
      <br />,
      <li>15.2 Swap variable, swap without temp, destructing</li>,
      <br />,
      <li>15.3 Random number, random number between 1 to 6</li>,
      <br />,
      <li>15.4 Find max of two values, find max of three values</li>,
      <br />,
      <li>15.5 Find the largest element of an array</li>,
      <br />,
      <li>15.6 Sum of all numbers in an array</li>,
      <br />,
      <li>15.7 Remove duplicate item from an array</li>,
      <br />,
      <li>15.8 Count the number of words in a string</li>,
      <br />,
      <li>15.9 Reverse a string</li>,
      <br />,
      <li>15.10 Module Summary</li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li>16.1 Problem Solving assignment</li>,
      <br />,
      <li>16.2 Problem Solving Assignment Updated</li>,
      <br />,
    ],
  },
  {
    id: 16.5,
    module: "16_5. Basic JavaScript Bonus Module",
    description: [
      <li>16_5.1 revisit Variablem, string, array, loop</li>,
      <br />,
      <li>16_5.2 Remove confusion with function and function vs loop</li>,
      <br />,
      <li>16_5.3 how recursion works and recursion vs iterative</li>,
      <br />,
      <li>16_5.4 Travelling in a Jungle and counting wild animals</li>,
      <br />,
      <li>16_5.5 Is Problem Solving Important Should I focus on it</li>,
      <br />,
    ],
  },
  {
    id: 17,
    module: "17. Serious Web Developer Productivity, Efficiency, Tips & Tricks",
    description: [
      <li>17.1 typing practice, typing lesson, typing test</li>,
      <br />,
      <li>
        17.2 developer question answer, Stack Overflow, weekly newsletter
      </li>,
      <br />,
      <li>17.3 Emmet, magic to write large amount HTML and CSS</li>,
      <br />,
      <li>17.4 Live server, automatic reload of the website after save</li>,
      <br />,
      <li>17.5 VSCode extension, JavaScript code snippet, ES linter</li>,
      <br />,
      <li>17.6 Visual Studio Code shortcut key, settings change</li>,
      <br />,
      <li>17.7 VS code multi cursor and multi line edit magic</li>,
      <br />,
      <li>17.8 Module Summary, keep updated about skills</li>,
      <br />,
    ],
  },
  {
    id: 18,
    module: "18. How Javascript Works & DOM",
    description: [
      <li>18.1 JavaScript and DOM Module Introduction</li>,
      <br />,
      <li>Quiz 18.1</li>,
      <br />,
      <li>18.2 Create Script tag and connect external Script file</li>,
      <br />,
      <li>Quiz 18.2 </li>,
      <br />,
      <li>18.3 How Javascript Run and why script order is important</li>,
      <br />,
      <li>Quiz 18.3</li>,
      <br />,
      <li>18.4 What is DOM (Document Object Model)</li>,
      <br />,
      <li>Quiz 18.4</li>,
      <br />,
      <li>18.5 Capture Elements from HTML File using getElementById</li>,
      <br />,
      <li>Quiz 18.5</li>,
      <br />,
      <li>18.6 how to use getElementsByClassName and change innerHTML</li>,
      <br />,
      <li>Quiz 18.6</li>,
      <br />,
      <li>18.7 How to use querySelector and querySelectorAll</li>,
      <br />,
      <li>Quiz 18.7</li>,
      <br />,
      <li>18.8 node, node type, nodelist, htmlcollection, setAttribute</li>,
      <br />,
      <li>Quiz 18.8</li>,
      <br />,
      <li>18.9 How to add elements to HTML using Javascript</li>,
      <br />,
      <li>Quiz 18.9</li>,
      <br />,
      <li>18.10 module summary Javascript and DOM</li>,
      <br />,
    ],
  },
  {
    id: 19,
    module: "19. Function, addEventListener, Event bubble",
    description: [
      <li>19.1 When to use a function, function inside an array</li>,
      <br />,
      <li>Quiz 19.1</li>,
      <br />,
      <li>19.2 When to return from a function and from where</li>,
      <br />,
      <li>Quiz 19.2</li>,
      <br />,
      <li>19.3 Callback function and pass different function</li>,
      <br />,
      <li>Quiz 19.3</li>,
      <br />,
      <li>19.4 arguments and deal with unknown number of arguments</li>,
      <br />,
      <li>Quiz 19.4</li>,
      <br />,
      <li>19.5 How to organize code inside a function</li>,
      <br />,
      <li>Quiz 19.5</li>,
      <br />,
      <li>19.6 What is Event, different types of event in web</li>,
      <br />,
      <li>Quiz 19.6</li>,
      <br />,
      <li>19.7 add event handler directly on an element</li>,
      <br />,
      <li>Quiz 19.7</li>,
      <br />,
      <li>19.8 add event listener using javascript</li>,
      <br />,
      <li>Quiz 19.8</li>,
      <br />,
      <li>19.9 Event bubble with example</li>,
      <br />,
      <li>Quiz 19.9</li>,
      <br />,
      <li>19.10 Stop propagating event bubble</li>,
      <br />,
      <li>19.11 Event delegate and purpose of Event bubble</li>,
      <br />,
      <li>19.12 Function, Event, Event bubble module summary</li>,
    ],
  },
  {
    id: 20,
    module: "20. Pioneer Bank, develop a simple bank website",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
  {
    id: 16,
    module: "16 Problem solving assignment",
    description: [
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
      <li></li>,
      <br />,
    ],
  },
];

export default data;
